version: '3.8'

services:
  compliance_mongodb:
    image: mongo
    container_name: compliance_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: aya
      MONGO_INITDB_ROOT_PASSWORD: dior
    volumes:
      - mongodb_data:/data/db

  compliance_app:
    build:
      context: ./compliance_app
    container_name: compliance_app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://aya:dior@compliance_mongodb:27017
    depends_on:
      - compliance_mongodb

volumes:
  mongodb_data:
